//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.01 at 02:47:35 PM GMT-03:00 
//


package cemantika.testing.cxg.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="from" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="to" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fromType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="toType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="bendpoints" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "connection")
public class Connection {

    @XmlAttribute(required = true)
    protected String from;
    @XmlAttribute(required = true)
    protected String to;
    @XmlAttribute
    protected String fromType;
    @XmlAttribute
    protected String toType;
    @XmlAttribute
    protected String bendpoints;

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrom(String value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTo(String value) {
        this.to = value;
    }

    /**
     * Gets the value of the fromType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromType() {
        return fromType;
    }

    /**
     * Sets the value of the fromType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromType(String value) {
        this.fromType = value;
    }

    /**
     * Gets the value of the toType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToType() {
        return toType;
    }

    /**
     * Sets the value of the toType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToType(String value) {
        this.toType = value;
    }

    /**
     * Gets the value of the bendpoints property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBendpoints() {
        return bendpoints;
    }

    /**
     * Sets the value of the bendpoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBendpoints(String value) {
        this.bendpoints = value;
    }

	@Override
	public String toString() {
		return "<connection from=" + this.getFrom() + " to="+ this.getTo()+" /> <!-- fromType="+ this.getFromType() + " toType="+ this.getToType() + "-->";
	}
    
    

}
