//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.01 at 02:47:35 PM GMT-03:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://drools.org/drools-5.0/process", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package cemantika.testing.cxg.xsd;
