//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.01 at 02:47:35 PM GMT-03:00 
//


package cemantika.testing.cxg.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://drools.org/drools-5.0/process}constraint"/>
 *         &lt;element ref="{http://drools.org/drools-5.0/process}eventFilters"/>
 *         &lt;element ref="{http://drools.org/drools-5.0/process}mapping"/>
 *       &lt;/choice>
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "constraintOrEventFiltersOrMapping"
})
@XmlRootElement(name = "trigger")
public class Trigger {

    @XmlElements({
        @XmlElement(name = "constraint", type = Constraint.class),
        @XmlElement(name = "eventFilters", type = EventFilters.class),
        @XmlElement(name = "mapping", type = Mapping.class)
    })
    protected List<Object> constraintOrEventFiltersOrMapping;
    @XmlAttribute(required = true)
    protected String type;

    /**
     * Gets the value of the constraintOrEventFiltersOrMapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the constraintOrEventFiltersOrMapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConstraintOrEventFiltersOrMapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Constraint }
     * {@link EventFilters }
     * {@link Mapping }
     * 
     * 
     */
    public List<Object> getConstraintOrEventFiltersOrMapping() {
        if (constraintOrEventFiltersOrMapping == null) {
            constraintOrEventFiltersOrMapping = new ArrayList<Object>();
        }
        return this.constraintOrEventFiltersOrMapping;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
